### ISSUE TITLE
시스템의 안정성 및 프로세스의 처리 흐름 처리를 위한 유지보수 로깅

### ISSUE THREAD

**Issue by siontext** [projectcleanroom/clean_back#34]
## 적용 페이지
* 없음

## 기능
* 시스템의 안정성 및 프로세스의 처리 흐름을 추적하기 위해
Logback Framework의 도입을 제안 및 도입하여 Application Logging Interface를 구축

## TODO
- [x] Logback을 이용한 로깅 구현하기
- [x] Logback 로컬 로깅 추가
- [x] 롤링 파일Appender 추가 구현
- [x] 롤링 정책 수립
- [x] INFO 레벨과 ERRROR레벨로 나누어 로그를 저장
- [x] console, file-info, file-error appender 들을 각각의 xml 파일로 분리
- [x] local 환경에서는 INFO 레벨 이상의 로그들이 작성되도록 분리
- [x] 그 외의 환경에서는 ERROR 레벨 이상의 로그들이 작성되도록 분리

**Comment by jhchoen** [comment]
로그 레벨 및 포맷이 어떻게 되었는지 추 후 공유 부탁 드립니다.
