### ISSUE TITLE
성능 테스트 개선 

### ISSUE THREAD

**Issue by siontext** [projectcleanroom/clean_back#95]
## 적용 페이지
* 청소의뢰 페이지

## 기능
* 성능 테스트 개선 

## TODO
- [x] 페치타입 ManyToOne 을→ 지연로딩으로 바꿔주어 
쿼리가 4번 나가는 것을 2번으로 줄이는 N+1 문제 해결.
- [x] 시간복잡도 측정 후 청소의뢰 로직에서 성능 저하가 일어나는 곳을 파악 후 개선
- [x] 네이티브 쿼리 사용으로 시간복잡도와 공간복잡도 확보
- [x] 내 청소의뢰 내역을 조회할때 캐싱을 사용하도록 적용
- [x] 청소 의뢰 생성, 수정, 취소 등 데이터의 변경이 일어났을 때는 캐시를 무효화
